### ISSUE TITLE
error while running get_wf.py

### ISSUE THREAD

**Issue by dianadahliah** [WMD-group/CarrierCapture.jl#11]

**Comment by frssp** [comment]
Can you provide more details?

**Comment by dianadahliah** [comment]
I figured out the solution, if I provided more than 3 paths of deformed geometry, the code will crash and show errors related to memory issues.  
  Is  band_index of ψ_i either the VBM index or CBM index for initial geometry (the relaxed vacancy in either state)?
and in  W_if calculation
what do you mean with : # # Central finite difference
diff = [1/12 -2/3 0 2/3 -1/12] * overlap / ΔQ?

**Comment by frssp** [comment]
- __Usually__, yes. See [this paper](https://link.aps.org/doi/10.1103/PhysRevB.90.075202) for more details.
- Those are the finite difference coefficients. See more [here](https://en.wikipedia.org/wiki/Finite_difference_coefficient).
