### ISSUE TITLE
 The question of install the carriercapture.jl

### ISSUE THREAD

**Issue by zhuhaoran-nku** [WMD-group/CarrierCapture.jl#12]
Now I have a problem about the installation of Carriercapture.jl code, the question as follow:
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At C:\ps_script\testjava.ps1:41 char:31
+           $client.DownloadFile <<<< ($source, $destination)
+ CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : DotNetMethodException + ERROR: Unable to automatically install 'LAME' from 'C:\Users\zhr\.julia\packages\LAME_jll\UzJad\Artifacts.toml' 
I don't know what causes this problem, and how to solve it.

**Comment by aronwalsh** [comment]
Hi. I see you are running on Windows. I assume you installed Julia first from https://julialang.org/downloads/?

**Comment by zhuhaoran-nku** [comment]
Yes, it is true.

**Comment by aronwalsh** [comment]
Closing after two years. We have no Windows machine to check, but it is not a CarrierCapture issue
