### ISSUE TITLE
calc_capt_coeff! function error

### ISSUE THREAD

**Issue by zb3lyp** [WMD-group/CarrierCapture.jl#19]
During the execution of the script, I received an error message, and I am uncertain about its root cause. The error message I encountered is as follows:

"Julia>   calc_overlap!(cc_e; cut_off = cut_off, σ = σ , Q₀   = 0)

 Julia> calc_capt_coeff!(cc_e, Volume, temperature)

ERROR: AssertionError: occ(ϵ_max, T_max): 2.0207251001010498e-5 should be less than 1.0e-5
Stacktrace:
 [1] calc_capt_coeff!(cc::conf_coord, V::Float64, temperature::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64})
   @ CarrierCapture C:\Users\9527\.julia\packages\CarrierCapture\RaoWA\src\CaptureRate.jl:118
 [2] top-level scope
   @ REPL[173]:1"

**Comment by frssp** [comment]
increase ‘nev’.

**Comment by zb3lyp** [comment]
Thanks, it works @frssp
