### ISSUE TITLE
Clarify installation instructions

### ISSUE THREAD

**Issue by taylor-a-barnes** [WMD-group/CarrierCapture.jl#3]
The installation instructions are straightforward enough for anyone with prior experience using Julia, but could potentially confuse others.  It would be worthwhile to clarify that the "Pkg.add" command should be executed (1) within the context of the Julia REPL and (2) after executing a "using Pkg" command.  Once users reach this point, you can rely on your examples to help ease them into the language.

**Comment by taylor-a-barnes** [comment]
This issue is part of https://github.com/openjournals/joss-reviews/issues/2102.

**Comment by frssp** [comment]
The installation instructions in `README.md` and the document.
