### ISSUE TITLE
Unify "Usage" and "Typical Usage" documentation

### ISSUE THREAD

**Issue by taylor-a-barnes** [WMD-group/CarrierCapture.jl#4]
The [documentation](https://wmd-group.github.io/CarrierCapture.jl/dev/) includes a section on "Usage".  In addition to this, there is a separate "Typical Usage" section in the [example](https://github.com/WMD-group/CarrierCapture.jl/tree/master/example) directory that goes into much more technical detail.  As far as I can tell, there are no links to this information anywhere else in the documentation; I only see a link to the `/example/notebook` subdirectory, which makes this easy to miss.  I recommend that you incorporate the information in `/example/README.md` more coherently into the documentation, either by linking to it prominently or by moving it elsewhere.

**Comment by taylor-a-barnes** [comment]
This issue is part of https://github.com/openjournals/joss-reviews/issues/2102.

**Comment by frssp** [comment]
`/example/README.md` is now in the Usage section in the documentation.
