### ISSUE TITLE
Who is Antonello Lobianco?

### ISSUE THREAD

**Issue by utf** [WMD-group/CarrierCapture.jl#8]
I'm sure he would be very pleased to know CarrierCapture.jl is licensed under his name...

https://github.com/WMD-group/CarrierCapture.jl/blob/9f99feaa840975437e09540ea5d36e6a6e7c3797/LICENCE#L3

Part of openjournals/joss-reviews#2102

**Comment by frssp** [comment]
I fixed the `LICENCE` file, before he notices this.
